# release-drafter.yml
name-template: "$NAME ($DATE)"
tag-template: "${{ github.ref_name }}"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "feat"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
      - "compat"
  - title: "Performance Improvements"
    labels:
      - "perf"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "Refactoring"
    labels:
      - "refactor"
  - title: "Tests"
    labels:
      - "test"
  - title: "Chores"
    labels:
      - "chore"
  - title: "CI"
    labels:
      - "ci"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

template: |
  ## $NAME ($DATE)

  $CHANGES

  ### Contributors
  $CONTRIBUTORS
